src/main/java/inscricao/entity/Candidato.java
package inscricao.entity;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 *
 * @author Wilson
 */
public class Candidato implements Serializable {
    private static final long serialVersionUID = 1L;
    private Long cpf;
    private String rg;
    private String nome;
    private String instituicao;
    private String programa;
    private String endereco;
    private String bairro;
    private String cidade;
    private String estado;
    private Integer cep;
    private String fone;
    private String celular;
    private String email;
    private Idioma idioma;
    private Date dataHora;

    public Candidato() {
    }

    public Candidato(Idioma idioma) {
        this.idioma = idioma;
    }

    public Candidato(Long cpf) {
        this.cpf = cpf;
    }

    public Long getCpf() {
        return cpf;
    }

    public void setCpf(Long cpf) {
        this.cpf = cpf;
    }

    public String getRg() {
        return rg;
    }

    public void setRg(String rg) {
        this.rg = rg;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getInstituicao() {
        return instituicao;
    }

    public void setInstituicao(String instituicao) {
        this.instituicao = instituicao;
    }

    public String getPrograma() {
        return programa;
    }

    public void setPrograma(String programa) {
        this.programa = programa;
    }

    public String getEndereco() {
        return endereco;
    }

    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    public String getBairro() {
        return bairro;
    }

    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    public String getCidade() {
        return cidade;
    }

    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public Integer getCep() {
        return cep;
    }

    public void setCep(Integer cep) {
        this.cep = cep;
    }

    public String getFone() {
        return fone;
    }

    public void setFone(String fone) {
        this.fone = fone;
    }

    public String getCelular() {
        return celular;
    }

    public void setCelular(String celular) {
        this.celular = celular;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Idioma getIdioma() {
        return idioma;
    }

    public void setIdioma(Idioma idioma) {
        this.idioma = idioma;
    }

    public Date getDataHora() {
        return dataHora;
    }

    public void setDataHora(Date dataHora) {
        this.dataHora = dataHora;
    }

}

src/main/java/inscricao/entity/Idioma.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package inscricao.entity;

import java.io.Serializable;

/**
 *
 * @author Wilson
 */
public class Idioma implements Serializable {
    private Integer codigo;
    private String descricao;

    public Idioma() {
    }

    public Idioma(Integer codigo) {
        this.codigo = codigo;
    }

    public Idioma(Integer codigo, String descricao) {
        this.codigo = codigo;
        this.descricao = descricao;
    }

    public Integer getCodigo() {
        return codigo;
    }

    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    public String getDescricao() {
        return descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

}

src/main/java/inscricao/faces/mngbeans/InscricaoBean.java
package inscricao.faces.mngbeans;

import inscricao.entity.Candidato;
import inscricao.entity.Idioma;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.enterprise.context.RequestScoped;
import javax.faces.model.SelectItem;
import javax.inject.Inject;
import javax.inject.Named;
import utfpr.faces.support.PageBean;

/**
 *
 * @author Wilson
 */
@Named
@RequestScoped
public class InscricaoBean extends PageBean {
    @Inject
    private RegistroBean registroBean;
    private static final Idioma[] IDIOMAS = {
        new Idioma(1, "Inglês"),
        new Idioma(2, "Alemão"),
        new Idioma(3, "Francês")
    };
    
    private Candidato candidato = new Candidato(IDIOMAS[0]); // inicialmente ingles
    private List<SelectItem> idiomaItemList;
    
    public Candidato getCandidato() {
        return candidato;
    }

    public void setCandidato(Candidato candidato) {
        this.candidato = candidato;
    }

    public Idioma[] getIdiomas() {
        return IDIOMAS;
    }
    
    public List<SelectItem> getIdiomaItemList() {
        if (idiomaItemList != null) return idiomaItemList;
        idiomaItemList = new ArrayList<>();
        for (Idioma id: IDIOMAS) {
            idiomaItemList.add(new SelectItem(id.getCodigo(), id.getDescricao()));
        }
        return idiomaItemList;
    }

    public String confirmaAction() {
        candidato.setDataHora(new Date());
        candidato.setIdioma(IDIOMAS[candidato.getIdioma().getCodigo()-1]);
        registroBean.addCandidato(candidato);
        return "confirma";
    }
}

src/main/java/inscricao/faces/mngbeans/RegistroBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inscricao.faces.mngbeans;

import inscricao.entity.Candidato;
import java.util.ArrayList;
import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.context.RequestScoped;
import javax.faces.model.ListDataModel;
import javax.inject.Named;

/**
 *
 * @author chris
 */
@Named
@ApplicationScoped
public class RegistroBean {
    ArrayList<Candidato> CandidatosList = new ArrayList<Candidato>();
    private final ListDataModel<Candidato> candidatoDataModel = new ListDataModel<>(CandidatosList);
    public void addCandidato(Candidato cand){
        CandidatosList.add(cand);
    }
    public RegistroBean(){}
    public ListDataModel<Candidato> getCandidatos(){
        return candidatoDataModel;
    }
}


src/main/java/utfpr/faces/support/ApplicationBean.java
/*
 * EXEMPLOS
 */
package utfpr.faces.support;


/**
 * O bean de aplicação
 * @author Wilson
 */
public class ApplicationBean extends FacesBean {
}

src/main/java/utfpr/faces/support/FacesBean.java
/*
 * === CLASSES DE APOIO JSF ===
 * Este código fonte pode ser livremente copiado, modificado e distribuído,
 * desde que esta mensagem seja preservada.
 * Todo o esforço foi feito para escrever um código correto e eficiente, entretanto o
 * autor não assume qualquer responsabilidade, direta ou indireta sobre a aplicabilidade
 * e/ou adequação a um fim específico e não garante que esteja livre de erros.
 * Copyright (C) 2009 <a href="http://www.utfpr.edu.br">Universidade Tecnológica Federal do Paraná</a>
 */

package utfpr.faces.support;

import java.io.Serializable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.servlet.ServletContext;
import javax.servlet.http.HttpSession;

/**
 * Classe base para os beans de aplicação, sessão, request e página.
 * @version 1.0.0
 *
 * @author Wilson Horstmeyer Bogado <wilson@utfpr.edu.br>
 * <a href="http://www.utfpr.edu.br">Universidade Tecnológica Federal do Paraná</a>
 */
public class FacesBean implements Serializable {

    private static final Logger logger = Logger.getLogger(PageBean.class.getName());

    /**
     * Retorna o <code>FacesContext</code> corrente.
     * @return O <code>FacesContext</code>
     */
    public FacesContext getFacesContext() {
        return FacesContext.getCurrentInstance();
    }

    /**
     * Retorna o contexto externo de JSF.
     * @return O contexto externo
     */
    public ExternalContext getExternalContext() {
        return getFacesContext().getExternalContext();
    }
    
    /**
     * Retorna ou cria uma sessão. 
     * @param create {@code true} para cria uma nova sessão, caso não exista
     * @return A sessão, ou null, caso não exista
     */
    public HttpSession getSession(boolean create) {
        return (HttpSession) getExternalContext().getSession(create);
    }
    
    /**
     * Retorna a sessão atual ou {@code null} caso não exista.
     * @return A sessão existente ou {@code null}
     */
    public HttpSession getSession() {
        return getSession(false);
    }
    
    /**
     * Retorna o contexto do servlet.
     * @return O contexto do servlet
     */
    public ServletContext getServletContext() {
        return (ServletContext) getExternalContext().getContext();
    }

    /**
     * Gera um log de informação com a mensagem especificada.
     * @param message A mensagem
     */
    public void log(String message) {
        logger.log(Level.INFO, message);
    }

    /**
     * Gera um log de erro com a mensagem e exceção especificadas.
     * @param message A mensagem
     * @param t A exceção
     */
    public void log(String message, Throwable t) {
        logger.log(Level.SEVERE, message, t);
    }
}

src/main/java/utfpr/faces/support/PageBean.java
/*
 * EXEMPLOS
 */
package utfpr.faces.support;

import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;

/**
 * Classe base dos managed beans de páginas JSF.
 * @author Wilson
 */
public class PageBean extends FacesBean {

    /**
     * Retorna um managed bean dado o seu nome
     * @return O bean de aplicação
     */
    public Object getBean(String name) {
        return getFacesContext().getApplication().evaluateExpressionGet(
            FacesContext.getCurrentInstance(), "#{" + name +  "}", Object.class);
    }

    /**
     * Gera uma mensagem de informação associada a um componente.
     * @param component O componente
     * @param message A mensagem
     */
    public void info(UIComponent component, String message) {
        getFacesContext().addMessage(component.getClientId(getFacesContext()),
            new FacesMessage(FacesMessage.SEVERITY_INFO, message, null));
    }

    /**
     * Gera uma mensagem de informação não associada a um componente.
     * @param message O <i>summary</i> da mensagem
     */
    public void info(String message) {
        getFacesContext().addMessage(null,
            new FacesMessage(FacesMessage.SEVERITY_INFO, message, null));
    }

    /**
     * Gera uma mensagem de advertência associada a um componente.
     * @param component O componente
     * @param message A mensagem
     */
    public void warn(UIComponent component, String message) {
        getFacesContext().addMessage(component.getClientId(getFacesContext()),
            new FacesMessage(FacesMessage.SEVERITY_WARN, message, null));
    }

    /**
     * Gera uma mensagem de advertência não associada a um componente.
     * @param message O <i>summary</i> da mensagem
     */
    public void warn(String message) {
        getFacesContext().addMessage(null,
            new FacesMessage(FacesMessage.SEVERITY_WARN, message, null));
    }

    /**
     * Gera uma mensagem de erro associada a um componente.
     * @param component O componente
     * @param message A mensagem
     */
    public void error(UIComponent component, String message) {
        getFacesContext().addMessage(component.getClientId(getFacesContext()),
            new FacesMessage(FacesMessage.SEVERITY_ERROR, message, null));
    }

    /**
     * Gera uma mensagem de erro não associada a um componente.
     * @param message <i>summary</i> da mensagem
     */
    public void error(String message) {
        getFacesContext().addMessage(null,
            new FacesMessage(FacesMessage.SEVERITY_ERROR, message, null));
    }
}

src/main/java/utfpr/faces/support/RequestBean.java
/*
 * === CLASSES DE APOIO JSF ===
 * Este código fonte pode ser livremente copiado, modificado e distribuído,
 * desde que esta mensagem seja preservada.
 * Todo o esforço foi feito para escrever um código correto e eficiente, entretanto o
 * autor não assume qualquer responsabilidade, direta ou indireta sobre a aplicabilidade
 * e/ou adequação a um fim específico e não garante que esteja livre de erros.
 * Copyright (C) 2009 <a href="http://www.utfpr.edu.br">Universidade Tecnológica Federal do Paraná</a>
 */

package utfpr.faces.support;

/**
 * Classe base para os beans de request.
 * @version 1.0.0
 *
 * @author Wilson Horstmeyer Bogado <wilson@dainf.ct.utfpr.edu.br>
 * <a href="http://www.utfpr.edu.br">Universidade Tecnológica Federal do Paraná</a>
 */
public class RequestBean extends PageBean {

}

src/main/java/utfpr/faces/support/SessionBean.java
/*
 * === CLASSES DE APOIO JSF ===
 * Este código fonte pode ser livremente copiado, modificado e distribuído,
 * desde que esta mensagem seja preservada.
 * Todo o esforço foi feito para escrever um código correto e eficiente, entretanto o
 * autor não assume qualquer responsabilidade, direta ou indireta sobre a aplicabilidade
 * e/ou adequação a um fim específico e não garante que esteja livre de erros.
 * Copyright (C) 2009 <a href="http://www.utfpr.edu.br">Universidade Tecnológica Federal do Paraná</a>
 */
package utfpr.faces.support;

/**
 * Classe base par o bean de sessão.
 * @version 1.0.0
 *
 * @author Wilson Horstmeyer Bogado <wilson@dainf.ct.utfpr.edu.br>
 * <a href="http://www.utfpr.edu.br">Universidade Tecnológica Federal do Paraná</a>
 */
public class SessionBean extends PageBean {
}

src/main/webapp/candidatos.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Candidatos</title>
    </h:head>
    <h:body>
        #{inscricaoBean.candidato.cpf}
        <h:dataTable value="#{registroBean.candidatos}" var="c"
    			border="1" rules="all" cellpadding="4"
    	>
            
    	<h:column><f:facet name="header">CPF</f:facet><h:outputText value="#{c.cpf}"/></h:column>
    	<h:column><f:facet name="header">Nome</f:facet><h:outputText value="#{c.nome}"/></h:column>
        <h:column><f:facet name="header">Cidade</f:facet><h:outputText value="#{c.cidade}"/></h:column>
        <h:column><f:facet name="header">Estado</f:facet><h:outputText value="#{c.estado}"/></h:column>
    			
        </h:dataTable>
    </h:body>
</html>

src/main/webapp/confirma.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                template="/WEB-INF/templates/layout.xhtml">

    <ui:define name="styles">
        <link href="#{request.contextPath}/css/inscricao.css" rel="stylesheet" type="text/css" />
    </ui:define>

    <ui:define name="metadata">
    </ui:define>

    <ui:define name="javascript">
    </ui:define>

    <ui:define name="content">
        <h:form>
            <div class="titulo-form">INSCRIÇÃO CONFIRMADA</div>
            Prezado(a) #{inscricaoBean.candidato.nome},<br/><br/>
            Seguem os dados da sua insrição<br/>
            Idioma escolhido: #{inscricaoBean.candidato.idioma.descricao}<br/>
            CPF: #{inscricaoBean.candidato.cpf}<br/>
            Data e hora:
            <h:outputText value="#{inscricaoBean.candidato.dataHora}">
                <f:convertDateTime dateStyle="full" locale="pt_BR"/>
            </h:outputText><br/>
            <div class="submit">
                <h:commandButton value="Voltar" action="inscricao"/>
            </div>
            <h:messages/>
        </h:form>
    </ui:define>

</ui:composition>

src/main/webapp/inscricao.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                template="/WEB-INF/templates/layout.xhtml">

    <ui:define name="styles">
        <link href="#{request.contextPath}/css/inscricao.css" rel="stylesheet" type="text/css" />
    </ui:define>

    <ui:define name="metadata">
    </ui:define>

    <ui:define name="javascript">
    </ui:define>

    <ui:define name="content">
        <h:form>
            <div class="titulo-form">FICHA DE INSCRIÇÃO</div>
            <h:panelGroup style="text-align: left; margin-bottom: 10px;" layout="block">
                <h:panelGroup styleClass="form-block" layout="block">
                    <h:outputLabel for="idioma" value="Idioma"/>
                    <h:selectOneMenu id="idioma" value="#{inscricaoBean.candidato.idioma.codigo}" style="width:12em">
                        <f:selectItems value="#{inscricaoBean.idiomas}" var="i" itemValue="#{i.codigo}" itemLabel="#{i.descricao}"/>
                    </h:selectOneMenu>
                </h:panelGroup>
                <h:panelGroup styleClass="form-block" layout="block">
                    <h:outputLabel for="cpf" value="CPF"/>
                    <h:inputText id="cpf" value="#{inscricaoBean.candidato.cpf}" label="CPF" size="15" maxlength="11" required="true"/>
                    <h:outputLabel for="rg" value="RG"/>
                    <h:inputText id="rg" value="#{inscricaoBean.candidato.rg}" size="25" label="RG" maxlength="20" required="true"/>
                </h:panelGroup>
                <h:panelGroup styleClass="form-block" layout="block">
                    <h:outputLabel for="nome" value="Nome"/>
                    <h:inputText id="nome" value="#{inscricaoBean.candidato.nome}" size="50"
                         label="Nome" maxlength="100" required="true"/>
                </h:panelGroup>
                <h:panelGroup styleClass="form-block" layout="block">
                    <h:outputLabel for="endereco" value="Endereço"/>
                    <h:inputText id="endereco" value="#{inscricaoBean.candidato.endereco}" size="50"
                          styleClass="ui-inputfield" label="Endereço" maxlength="80" required="true"/>
                </h:panelGroup>
                <h:panelGroup styleClass="form-block" layout="block">
                    <h:outputLabel for="cidade" value="Cidade"/>
                    <h:inputText id="cidade" value="#{inscricaoBean.candidato.cidade}" size="50"
                                 label="Cidade" maxlength="50" required="true"/>
                    <h:outputLabel for="estado" value="Estado"/>
                    <h:selectOneMenu id="estado" value="#{inscricaoBean.candidato.estado}" label="Estado" required="true">
                        <f:selectItem itemLabel="" itemValue="${null}" noSelectionOption="true"/>
                        <f:selectItem itemLabel="AC" itemValue="AC"/>
                        <f:selectItem itemLabel="AL" itemValue="AL"/>
                        <f:selectItem itemLabel="AM" itemValue="AM"/>
                        <f:selectItem itemLabel="AP" itemValue="AP"/>
                        <f:selectItem itemLabel="BA" itemValue="BA"/>
                        <f:selectItem itemLabel="CE" itemValue="CE"/>
                        <f:selectItem itemLabel="DF" itemValue="DF"/>
                        <f:selectItem itemLabel="ES" itemValue="ES"/>
                        <f:selectItem itemLabel="GO" itemValue="GO"/>
                        <f:selectItem itemLabel="MA" itemValue="MA"/>
                        <f:selectItem itemLabel="MG" itemValue="MG"/>
                        <f:selectItem itemLabel="MS" itemValue="MS"/>
                        <f:selectItem itemLabel="MT" itemValue="MT"/>
                        <f:selectItem itemLabel="PA" itemValue="PA"/>
                        <f:selectItem itemLabel="PB" itemValue="PB"/>
                        <f:selectItem itemLabel="PE" itemValue="PE"/>
                        <f:selectItem itemLabel="PI" itemValue="PI"/>
                        <f:selectItem itemLabel="PR" itemValue="PR"/>
                        <f:selectItem itemLabel="RJ" itemValue="RJ"/>
                        <f:selectItem itemLabel="RN" itemValue="RN"/>
                        <f:selectItem itemLabel="RO" itemValue="RO"/>
                        <f:selectItem itemLabel="RR" itemValue="RR"/>
                        <f:selectItem itemLabel="RS" itemValue="RS"/>
                        <f:selectItem itemLabel="SC" itemValue="SC"/>
                        <f:selectItem itemLabel="SE" itemValue="SE"/>
                        <f:selectItem itemLabel="SP" itemValue="SP"/>
                        <f:selectItem itemLabel="TO" itemValue="TO"/>
                    </h:selectOneMenu>
                </h:panelGroup>
                <h:panelGroup styleClass="form-block" layout="block">
                    <h:outputLabel for="cep" value="CEP"/>
                    <h:inputText id="cep" value="#{inscricaoBean.candidato.cep}" label="CEP" size="10" maxlength="8" required="true"/>
                    <h:outputLabel for="bairro" value="Bairro"/>
                    <h:inputText id="bairro" value="#{inscricaoBean.candidato.bairro}" size="30" label="Bairro" maxlength="50"/>
                </h:panelGroup>
                <h:panelGroup styleClass="form-block" layout="block">
                    <h:outputLabel for="fone" value="Fone"/>
                    <h:inputText id="fone" value="#{inscricaoBean.candidato.fone}" label="Fone" size="15"/>
                    <h:outputLabel for="celular" value="Celular"/>
                    <h:inputText id="celular" value="#{inscricaoBean.candidato.celular}" label="Celular" size="15"/>
                </h:panelGroup>
                <h:panelGroup styleClass="form-block" layout="block">
                    <h:outputLabel for="email" value="E-mail"/>
                    <h:inputText id="email" value="#{inscricaoBean.candidato.email}" size="80"
                          label="E-mail" maxlength="200" required="true"/>
                </h:panelGroup>
                <h:panelGroup styleClass="form-block" layout="block">
                    <h:outputLabel for="instituicao" value="Instituição"/>
                    <h:inputText id="instituicao" value="#{inscricaoBean.candidato.instituicao}" size="80"
                          label="Instituição" maxlength="100" required="true"/>
                </h:panelGroup>
                <h:panelGroup styleClass="form-block" layout="block">
                    <h:outputLabel for="programa" value="Programa"/>
                    <h:inputText id="programa" value="#{inscricaoBean.candidato.programa}" size="80"
                          label="Programa" maxlength="100" required="true"/>
                </h:panelGroup>
            </h:panelGroup>
            <div class="submit">
                <h:commandButton value="Confirmar Inscrição" action="#{inscricaoBean.confirmaAction}" />
            </div>
            <h:messages/>
        </h:form>
    </ui:define>

</ui:composition>